name: Build hanzo-node docker image

on:
  push:
    branches:
      - 'main'
      - 'devops'
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build-and-deploy:
    uses: dcSpark/hanzo-node/.github/workflows/build-workflow.yml@devops
    with:
      REGISTRY: dcspark
      REPOSITORY: hanzo-node
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      